### PR TITLE
Update to solutions notebook

### PR DESCRIPTION
**Pull request by kcecco**

### CODE REVIEW

**Comment by chanskw** [comment]
This pull request has conflict.  Katrina, can you please resolve the conflict?
I am unsure how we get to a conflict situation so not sure how to resolve.

**Comment by kcecco** [comment]
Ok... it is showing no issues now
 
Katrina Cecco
IBM Streams Enablement
E-mail: katrina.cecco@ibm.com
 
 
----- Original message -----From: Samantha Chan <notifications@github.com>To: IBMStreams/tutorials <tutorials@noreply.github.com>Cc: kcibm <katrina.cecco@ibm.com>, Author <author@noreply.github.com>Subject: Re: [IBMStreams/tutorials] Update to solutions notebook (#41)Date: Wed, Jun 7, 2017 3:28 PM 
This pull request has conflict. Katrina, can you please resolve the conflict?I am unsure how we get to a conflict situation so not sure how to resolve.

**Comment by chanskw** [comment]
but the pull request is closed, so I cannot merge.  Can you please reopen?

**Comment by kcecco** [comment]
I opened a new one... #42. Ignore the first one
 
Katrina Cecco
IBM Streams Enablement
E-mail: katrina.cecco@ibm.com
 
 
----- Original message -----From: Samantha Chan <notifications@github.com>To: IBMStreams/tutorials <tutorials@noreply.github.com>Cc: kcibm <katrina.cecco@ibm.com>, State change <state_change@noreply.github.com>Subject: Re: [IBMStreams/tutorials] Update to solutions notebook (#41)Date: Wed, Jun 7, 2017 5:49 PM 
but the pull request is closed, so I cannot merge. Can you please reopen?

**Pull request closed without merging**
